// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-ent-example/api/gen/go/common/conf"
	"kratos-ent-example/app/user/service/internal/data"
	"kratos-ent-example/app/user/service/internal/server"
	"kratos-ent-example/app/user/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	entClient := data.NewEntClient(bootstrap, logger)
	client := data.NewRedisClient(bootstrap, logger)
	dataData, cleanup, err := data.NewData(entClient, client, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userService := service.NewUserService(logger, userRepo)
	grpcServer := server.NewGRPCServer(bootstrap, logger, userService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
